formatting and misc changes

diff --git a/template b/template
--- a/template
+++ b/template
@@ -13,7 +13,9 @@ dir=""
 cmd=""
 user=""
 
-name=`basename $0`
+mypid=""
+
+name="$(basename "$0")"
 pid_file="/var/run/$name.pid"
 stdout_log="/var/log/$name.log"
 stderr_log="/var/log/$name.err"
@@ -23,76 +25,82 @@ get_pid() {
 }
 
 is_running() {
-    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
+    [ -f "$pid_file" ] && ps "$(get_pid)" 1>/dev/null 2>/dev/null
 }
 
-case "$1" in
-    start)
-    if is_running; then
-        echo "Already started"
-    else
-        echo "Starting $name"
-        cd "$dir"
-        if [ -z "$user" ]; then
-            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
-        else
-            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
-        fi
-        echo $! > "$pid_file"
-        if ! is_running; then
-            echo "Unable to start, see $stdout_log and $stderr_log"
-            exit 1
-        fi
-    fi
-    ;;
-    stop)
-    if is_running; then
-        echo -n "Stopping $name.."
-        kill `get_pid`
-        for i in {1..10}
-        do
-            if ! is_running; then
-                break
+main() {
+    case "$1" in
+        start)
+            if is_running; then
+                echo "Already started"
+            else
+                echo "Starting $name"
+                cd "$dir"
+                if [ -z "$user" ]; then
+                    # run as root if nothing specified
+                    sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
+                    mypid=$!
+                else
+                    sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
+                    mypid=$!
+                fi
+                echo -n "$mypid" > "$pid_file"
+                if ! is_running; then
+                    echo "Unable to start, see $stdout_log and $stderr_log"
+                    exit 1
+                fi
             fi
+            ;;
+        stop)
+            if is_running; then
+                echo -n "Stopping $name.."
+                kill "$(get_pid)"
+                for i in 1 2 3 4 5 6 7 8 9 10
+                do
+                    if ! is_running; then
+                        break
+                    fi
 
-            echo -n "."
-            sleep 1
-        done
-        echo
+                    echo -n "."
+                    sleep 1
+                done
+                echo
 
-        if is_running; then
-            echo "Not stopped; may still be shutting down or shutdown may have failed"
-            exit 1
-        else
-            echo "Stopped"
-            if [ -f "$pid_file" ]; then
-                rm "$pid_file"
+                if is_running; then
+                    echo "Not stopped; may still be shutting down or shutdown may have failed"
+                    exit 1
+                else
+                    echo "Stopped"
+                    if [ -f "$pid_file" ]; then
+                        rm "$pid_file"
+                    fi
+                fi
+            else
+                echo "Not running"
             fi
-        fi
-    else
-        echo "Not running"
-    fi
-    ;;
-    restart)
-    $0 stop
-    if is_running; then
-        echo "Unable to stop, will not attempt to start"
-        exit 1
-    fi
-    $0 start
-    ;;
-    status)
-    if is_running; then
-        echo "Running"
-    else
-        echo "Stopped"
-        exit 1
-    fi
-    ;;
-    *)
-    echo "Usage: $0 {start|stop|restart|status}"
-    exit 1
-    ;;
-esac
+            ;;
+        restart)
+            main stop
+            if is_running; then
+                echo "Unable to stop, will not attempt to start"
+                exit 1
+            fi
+            main start
+            ;;
+        status)
+            if is_running; then
+                echo "Running"
+            else
+                echo "Stopped"
+                exit 1
+            fi
+            ;;
+        *)
+            echo "Usage: $0 {start|stop|restart|status}"
+            exit 1
+            ;;
+    esac
+}
 
+main "$1"
 exit 0
